import PhonelinkIcon from '@mui/icons-material/Phonelink';
import EmailOutlinedIcon from '@mui/icons-material/EmailOutlined';
import WorkOutlineOutlinedIcon from '@mui/icons-material/WorkOutlineOutlined';
import SchoolOutlinedIcon from '@mui/icons-material/SchoolOutlined';
import LanguageOutlinedIcon from '@mui/icons-material/LanguageOutlined';
import LibraryBooksOutlinedIcon from '@mui/icons-material/LibraryBooksOutlined';

export  const skills = [
  { icon: <PhonelinkIcon className='iconHover' sx={{ fontSize: '54px', color: { xs: '#fff', sm: '#3b82f6' } }} />, title: 'Landing Pages', desc:( <> I build fast, focused pages using <strong style={{fontWeight:900}}>HTML</strong>, <strong style={{fontWeight:900}}>CSS</strong>, and <strong style={{fontWeight:900}}>JavaScript</strong>.  Most of my work is centered around signup flows, form logic, and clean structure that keeps things simple and effective.</> )},
  { icon: <LanguageOutlinedIcon className='iconHover' sx={{ fontSize: '54px', color: { xs: '#fff', sm: '#3b82f6' } }} />, title: 'Blog Websites', desc: (<>I create responsive blog websites with <strong style={{fontWeight:900}}>React</strong> and connect them to <strong style={{fontWeight:900}}>WordPress</strong> as a content backend. This setup keeps the frontend modern while making content easy to manage. </>)},
  {icon: <EmailOutlinedIcon className='iconHover' sx={{ fontSize: '54px', color: { xs: '#fff', sm: '#3b82f6' } }} />, title: 'Email Templates', desc:(<> I design and code email templates using <strong style={{fontWeight:900}}>table-based</strong> layouts to ensure they work everywhere. Tested across <strong style={{fontWeight:900}}>Gmail</strong>, <strong style={{fontWeight:900}}>Outlook</strong>, and older email clients where consistency really matters.</>)},
  { icon: <WorkOutlineOutlinedIcon className='iconHover' sx={{ fontSize: '54px', color: { xs: '#fff', sm: '#3b82f6' } }} />, title: 'Marketing Developer', desc:(<> I understand how users think, where to place <strong style={{fontWeight:900}}>calls to action</strong>, and how to guide attention. My work combines <strong style={{fontWeight:900}}>frontend</strong> skills with strong <strong style={{fontWeight:900}}>SEO</strong> and conversion-focused structure.</>) },
  { icon: <LibraryBooksOutlinedIcon className='iconHover' sx={{ fontSize: '54px', color: { xs: '#fff', sm: '#3b82f6' } }} />, title: 'WordPress Pages', desc: (<> I maintain and build larger <strong style={{fontWeight:900}}>WordPress</strong> websites, including <strong style={{fontWeight:900}}>custom themes</strong> and backend usage. Comfortable working with <strong style={{fontWeight:900}}>PHP</strong> basics, plugins, and using WordPress beyond just page builders.</>) },
  { icon: <SchoolOutlinedIcon className='iconHover' sx={{ fontSize: '54px', color: { xs: '#fff', sm: '#3b82f6' } }} />, title: 'Self-Taught Dev', desc: 'Most of what I know comes from learning by doing. I built my skills independently, supported by a technical education background and a lot of real-world practice.' }
]